package function.adminer.add_course.select_teacher;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import component.TeacherRanderer;
import data.user.Teacher;
import util.JFrameUtilKt;
import util.StackFrame;

import javax.swing.*;
import java.awt.*;
import java.util.Vector;

/**
 * Created by qiao1 on 2017/1/3.
 */
public class SelectTeacherAct extends StackFrame {
    private JPanel mPanelRoot;
    private JButton mBtnSubmit;
    private JButton mBtnCancel;
    private JList mList;
    private Vector<Teacher> mData;

    private SelectTeacherPresenter mPresenter;

    public SelectTeacherAct(SelectTeacherPresenter presenter) {
        super("选择任课教师");
        mPresenter = presenter;
        setContentPane(mPanelRoot);
        JFrameUtilKt.init(this, 450, 600);
        initData();
        initEvent();
    }

    private void initEvent() {
        mBtnCancel.addActionListener(l -> dispose());
        mBtnSubmit.addActionListener(l -> {
//            submitData(0x123, mList.getSelectedIndices());
            Vector<Teacher> selected = new Vector<>();
            for (int i = 0; i < mList.getSelectedIndices().length; i++) {
                selected.add(mData.get(mList.getSelectedIndices()[i]));     //把被选取的老师添加到Vectoer中
            }
            submitData(0x123, selected);
            dispose();
        });
    }

    private void initData() {
        mList.setCellRenderer(new TeacherRanderer());
        mData = mPresenter.queryAllTeachers();
        mList.setListData(mData);
    }


    @Override
    public void onDispose() {
        mPresenter.destroy();
        super.onDispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mPanelRoot = new JPanel();
        mPanelRoot.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mPanelRoot.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, BorderLayout.SOUTH);
        mBtnSubmit = new JButton();
        mBtnSubmit.setFont(new Font(mBtnSubmit.getFont().getName(), mBtnSubmit.getFont().getStyle(), 18));
        mBtnSubmit.setText("确定");
        panel2.add(mBtnSubmit, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mBtnCancel = new JButton();
        mBtnCancel.setFont(new Font(mBtnCancel.getFont().getName(), mBtnCancel.getFont().getStyle(), 18));
        mBtnCancel.setText("取消");
        panel2.add(mBtnCancel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        mList = new JList();
        panel1.add(mList, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mPanelRoot;
    }
}
